config/routes.rb
Coachio::Application.routes.draw do

  devise_for :users

  resources :teams do
    match "practices" => "teams#practices"
    resources :activities
    resources :goals do
      resources :progresses
    end
    resources :members
    resources :workouts do
      resources :practices do
        resources :results # Not sure I need these routes, probably just handle it in practice
        get 'complete', :on => :member
      end
      resources :plans
    end
  end
  
  root :to => "home#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :team
  has_many :plans
  has_many :workouts, :through => :plans
  attr_accessible :group, :minutes, :name
  validates :name,  :presence => true
  
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :team
  has_many :progresses
  attr_accessible :active, :description, :name, :team
  validates :name,  :presence => true
  
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :team
  has_many :practices
  attr_accessible :first_name, :last_name, :number, :player, :position
  validates :first_name,  :presence => true
  validates :last_name,  :presence => true
  
  def name
    first_name + ' ' + last_name
  end
  
  def practice_results
    results = practices.collect{|p| p.results}
    puts results
    if results
      results.flatten.sort!{|a,b| a.plan_id <=> b.plan_id }
    else
      results
    end
  end
  
  
  def practice_results2
    results = practices.collect{|p| p.results}
    puts results
    if results
      results.flatten.sort!{|a,b| a.plan_id <=> b.plan_id }
    else
      results
    end
  end
  
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :activity
  belongs_to :workout
  has_many :practices
  default_scope :order => 'position ASC'
  attr_accessible :activity_id, :individual, :public, :workout_id, :position, :minutes , :reps
  validates :activity_id,  :presence => true
  #Not sure why but this fails the workout create, probably because its checking on build not save
  #validates :workout_id,  :presence => true
  
  def minutes
    activity.minutes
  end
end

app/models/practice.rb
class Practice < ActiveRecord::Base
  belongs_to :team
  belongs_to :member
  belongs_to :workout
  has_many :results
  accepts_nested_attributes_for :results,
      :allow_destroy => true,
      :reject_if     => :all_blank
  attr_accessible :scheduled_date, :scheduled_time, :track_results, :member_id, :complete, :notes, :results_attributes
  
  def results_totals
    # Get the totals of each activity totalled up
    puts 'hiii'
  end
  
end

app/models/progress.rb
class Progress < ActiveRecord::Base
  belongs_to :goal
  belongs_to :member
  attr_accessible :made, :total, :member_id
  validates :member_id,  :presence => true
  
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :practice
  belongs_to :plan
  attr_accessible :reps, :plan_id
  
  
  
  # Make methods for these then we can references them in the forms...
  def activity_name
    plan.activity.name
  end
  
  def plan_reps
    plan.reps
    #practice.workout.plans.find_by_activity_id(plan.activity.id).reps
  end
  
  
  def plan_position
    puts plan.to_json
    plan.position
    #practice.workout.plans.find_by_activity_id(plan.activity.id).position
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :city, :mascot, :name, :state, :kind, :description
  validates :name,  :presence => true
  has_many :members
  has_many :activities
  has_many :workouts
  has_many :goals
  has_many :practices

  def plans
    workouts.collect{|w| w.plans }.flatten
  end

  def location
    city + ', ' + state
  end
  
  def team_name
    name + ' ' + mascot
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :team
  has_many :practices
  has_many :plans
  has_many :activities, :through => :plans
  accepts_nested_attributes_for :plans,
      :allow_destroy => true,
      :reject_if     => :all_blank
  attr_accessible :group, :name, :plans_attributes
  validates :name,  :presence => true
  
  def length
    plans.collect{|p| p.minutes}.sum
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  # GET /workouts
  # GET /workouts.json
  def index
    @team = Team.find(params[:team_id])
    @workouts = @team.workouts

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workouts }
    end
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
    @team = Team.find(params[:team_id])
    @workout = @team.workouts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workout }
    end
  end

  # GET /workouts/new
  # GET /workouts/new.json
  def new
    @team = Team.find(params[:team_id])
    @workout = @team.workouts.new(:group => true)
    @activities = @team.activities
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workout }
    end
  end

  # GET /workouts/1/edit
  def edit
    @team = Team.find(params[:team_id])
    @workout = @team.workouts.find(params[:id])
    @activities = @team.activities    
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @team = Team.find(params[:team_id])
    @workout = @team.workouts.new(params[:workout])
    @activities = @team.activities
    puts @workout
    respond_to do |format|
      if @workout.save
        format.html { redirect_to team_workouts_path(@team), notice: 'workout was successfully created.' }
        format.json { render json: @workout, status: :created, location: @workout }
      else
        format.html { render action: "new" }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workouts/1
  # PUT /workouts/1.json
  def update
    @team = Team.find(params[:team_id])
    @workout = @team.workouts.find(params[:id])

    respond_to do |format|
      if @workout.update_attributes(params[:workout])
        format.html { redirect_to team_workout_path(@team, @workout), notice: 'workout was successfully created.' }
        #format.html { redirect_to @workout, notice: 'workout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout = workout.find(params[:id])
    @workout.destroy

    respond_to do |format|
      format.html { redirect_to workouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def setup_workout(workout)
    # Add extra activities to the plan
    2.times { workout.plans.build() }
    puts workout
    workout
  end
end

app/views/workouts/_form.html.erb
<%= form_for([@team, setup_workout(@workout)]) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :group, 'Group Workout? uncheck for individuals', :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :group %>
    </div>
  </div>

<table class="table table-bordered"><thead><tr>
<th>Order</th>
	<th>Activity</th>
	<th>Minutes</th>
	<th>Reps</th>
	<th>Delete</th></tr></thead><tbody>
  <%= f.fields_for :plans do |ff| %>
    <tr>
	<td>
	    <%= ff.number_field :position %>
	</td><td>	  <%= ff.select :activity_id, @activities.collect {|w| [w.name, w.id]}, { :include_blank => true} %>
	</td><td>		<%= ff.number_field :minutes %>
	</td><td>		<%= ff.number_field :reps %>
      <% if ff.object.persisted? %>
    	</td><td>    <%= ff.check_box :_destroy %>
		<% else %>
		</td><td>
      <% end %>
    </td></tr>
  <% end %></tbody>
</table>


  <div class="actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render 'form' %>

<%= link_to 'Show', edit_team_workout_path(@team, @workout) %> |
<%= link_to 'Back', team_workouts_path(@team) %>

app/views/workouts/index.html.erb
<div class="page-header">
	<h1>Listing workouts</h1>
</div>

<p>This is your collection of workouts. Once workouts are created you may assign them to the team or players accordingly.  We keep all the workouts so you can reuse them later on.</p>

<% if @workouts.empty? %>
<h3>No workouts yet. Let's add one!</h3>
<% else %>
<table class="table table-striped">
<thead>  <tr>
    <th>Name</th>
    <th>Group</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead><tbody>
<% @workouts.each do |workout| %>
  <tr>
    <td><%= workout.name %></td>
    <td><%= workout.group %></td>
    <td><%= link_to 'Schedule', new_team_workout_practice_path(@team, workout) %></td>
    <td><%= link_to 'Planned', team_workout_practices_path(@team, workout) %></td>
    <td><%= link_to 'Show', team_workout_path(@team, workout) %></td>
    <td><%= link_to 'Edit', edit_team_workout_path(@team, workout) %></td>
    <td><%= link_to 'Destroy', team_workout_path(@team, workout), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %></tbody>
</table>
<% end %>


<div class="page-actions">
<% if @team.activities.empty? %>
			<%= link_to 'Add Activities before creating a workout', new_team_activity_path(@team), :class => 'btn btn-primary' %>
<% else %>
			<%= link_to 'New Workout', new_team_workout_path(@team), :class => 'btn btn-primary' %>
<% end %>
</div>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render 'form' %>

<%= link_to 'Back', team_workouts_path(@team) %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @workout.name %></h2>

<p>
  <b>Group:</b>
  <%= @workout.group %>
</p>

<%= link_to 'Edit', edit_team_workout_path(@team, @workout) %>

<ol>
<% @workout.plans.each do |plan| %>
	<li><%= link_to plan.activity.name, team_activity_path(@team, plan.activity) %> (<%= plan.minutes %> minutes)</li>
<%	end %>
</ol>


<%= link_to 'Back', team_workouts_path(@team) %>