config/routes.rb
Coachio::Application.routes.draw do

  devise_for :users

  resources :teams do
    match "practices" => "teams#practices"
    resources :activities
    resources :goals do
      resources :progresses
    end
    resources :members
    resources :workouts do
      resources :practices do
        resources :results # Not sure I need these routes, probably just handle it in practice
        get 'complete', :on => :member
      end
      resources :plans
    end
  end
  
  root :to => "home#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :team
  has_many :plans
  has_many :workouts, :through => :plans
  attr_accessible :group, :minutes, :name
  validates :name,  :presence => true
  
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :team
  has_many :progresses
  attr_accessible :active, :description, :name, :team
  validates :name,  :presence => true
  
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :team
  has_many :practices
  attr_accessible :first_name, :last_name, :number, :player, :position
  validates :first_name,  :presence => true
  validates :last_name,  :presence => true
  
  def name
    first_name + ' ' + last_name
  end
  
  def practice_results
    results = practices.collect{|p| p.results}
    puts results
    if results
      results.flatten.sort!{|a,b| a.plan_id <=> b.plan_id }
    else
      results
    end
  end
  
  
  def practice_results2
    results = practices.collect{|p| p.results}
    puts results
    if results
      results.flatten.sort!{|a,b| a.plan_id <=> b.plan_id }
    else
      results
    end
  end
  
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :activity
  belongs_to :workout
  has_many :practices
  default_scope :order => 'position ASC'
  attr_accessible :activity_id, :individual, :public, :workout_id, :position, :minutes , :reps
  validates :activity_id,  :presence => true
  #Not sure why but this fails the workout create, probably because its checking on build not save
  #validates :workout_id,  :presence => true
  
  def minutes
    activity.minutes
  end
end

app/models/practice.rb
class Practice < ActiveRecord::Base
  belongs_to :team
  belongs_to :member
  belongs_to :workout
  has_many :results
  accepts_nested_attributes_for :results,
      :allow_destroy => true,
      :reject_if     => :all_blank
  attr_accessible :scheduled_date, :scheduled_time, :track_results, :member_id, :complete, :notes, :results_attributes
  
  def results_totals
    # Get the totals of each activity totalled up
    puts 'hiii'
  end
  
end

app/models/progress.rb
class Progress < ActiveRecord::Base
  belongs_to :goal
  belongs_to :member
  attr_accessible :made, :total, :member_id
  validates :member_id,  :presence => true
  
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :practice
  belongs_to :plan
  attr_accessible :reps, :plan_id
  
  
  
  # Make methods for these then we can references them in the forms...
  def activity_name
    plan.activity.name
  end
  
  def plan_reps
    plan.reps
    #practice.workout.plans.find_by_activity_id(plan.activity.id).reps
  end
  
  
  def plan_position
    puts plan.to_json
    plan.position
    #practice.workout.plans.find_by_activity_id(plan.activity.id).position
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :city, :mascot, :name, :state, :kind, :description
  validates :name,  :presence => true
  has_many :members
  has_many :activities
  has_many :workouts
  has_many :goals
  has_many :practices

  def plans
    workouts.collect{|w| w.plans }.flatten
  end

  def location
    city + ', ' + state
  end
  
  def team_name
    name + ' ' + mascot
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :team
  has_many :practices
  has_many :plans
  has_many :activities, :through => :plans
  accepts_nested_attributes_for :plans,
      :allow_destroy => true,
      :reject_if     => :all_blank
  attr_accessible :group, :name, :plans_attributes
  validates :name,  :presence => true
  
  def length
    plans.collect{|p| p.minutes}.sum
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  # GET /practices
  # GET /practices.json
  def index
    @team = Team.find(params[:team_id])
    @workout = @team.workouts.find(params[:workout_id])
    @practices = @workout.practices

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @practices }
    end
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
    @team = Team.find(params[:team_id])
    @workout = @team.workouts.find(params[:workout_id])
    @practice = @workout.practices.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @practice }
    end
  end

  # GET /practices/new
  # GET /practices/new.json
  def new
    @team = Team.find(params[:team_id])
    @workouts = @team.workouts
    @workout = @team.workouts.find(params[:workout_id])
    @practice = @workout.practices.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @practice }
    end
  end

  # GET /practices/1/edit
  def edit
    @team = Team.find(params[:team_id])
    @workouts = @team.workouts
    @workout = @team.workouts.find(params[:workout_id])
    @practice = @workout.practices.find(params[:id])
  end

  # GET /practices/1/edit
  def complete
    @team = Team.find(params[:team_id])
    @workouts = @team.workouts
    @workout = @team.workouts.find(params[:workout_id])
    @practice = @workout.practices.find(params[:id])
    @practice.complete = true
    @workout.plans.each do |p|
      puts p
      @practice.results.build(:plan_id => p.id)
    end
    puts @practice.results
  end

  # POST /practices
  # POST /practices.json
  def create
    @team = Team.find(params[:team_id])
    @workout = @team.workouts.find(params[:workout_id])
    @practice = @workout.practices.new(params[:practice])
    @practice.team = @team

    respond_to do |format|
      if @practice.save
        format.html { redirect_to team_workout_practices_path(@team, @workout), notice: 'Practice was successfully created.' }
        format.json { render json: @practice, status: :created, location: @practice }
      else
        format.html { render action: "new" }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /practices/1
  # PUT /practices/1.json
  def update
    @team = Team.find(params[:team_id])
    @workout = @team.workouts.find(params[:workout_id])
    @practice = @workout.practices.find(params[:id])

    respond_to do |format|
      if @practice.update_attributes(params[:practice])
        format.html { redirect_to team_workout_practices_path(@team, @workout), notice: 'Practice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @team = Team.find(params[:team_id])
    @workout = @team.workouts.find(params[:workout_id])
    @practice = @workout.practices.find(params[:id])
    @practice.destroy

    respond_to do |format|
      format.html { redirect_to team_workout_practices_url(@team, @workout) }
      format.json { head :no_content }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def setup_workout(workout)
    # Add extra activities to the plan
    2.times { workout.plans.build() }
    puts workout
    workout
  end
end

app/views/practices/_complete_form.html.erb
<%= form_for([@team, @workout, @practice], :html => { :class => 'form-horizontal' }) do |f| %>
  <% if @practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
      <% @practice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<% if @practice.track_results %>

	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Order</th>
				<th>Activity</th>
				<th>Made</th>
				<th>Max Reps</th>
			</tr>
		</thead>
		<tbody>
	  	<%= f.fields_for :results do |ff| %>
	    <tr>
				<td>
					<%= ff.number_field :plan_position, :disabled => 'disabled' %>
				</td>
				<td>
					<%= ff.text_field :activity_name, :disabled => 'disabled' %>
				</td>
				<td>
					<%= ff.number_field :reps %><%= ff.hidden_field :plan_id %>
				</td>
				<td>
					<%= ff.number_field :plan_reps, :class => 'number_field', :disabled => 'disabled' %>
				</td>
		</tr>
	  <% end %></tbody>
	</table>

	<% end %>
  <div class="control-group">
    <%= f.label :notes, 'Practice Notes:', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :notes %><%= f.hidden_field :complete %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit 'Complete Practice', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/practices/_form.html.erb
<%= form_for([@team, @workout, @practice], :html => { :class => 'form-horizontal' }) do |f| %>
  <% if @practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
      <% @practice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :scheduled_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :scheduled_date %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :scheduled_time, :class => 'control-label' %>
    <div class="controls">
      <%= f.time_select :scheduled_time %>
    </div>
  </div>

	<% unless @workout.group %>
  <div class="control-group">
    <%= f.label :member, :class => 'control-label' %>
    <div class="controls">
			<%= f.select :member_id, @team.members.collect {|w| [w.name, w.id]} %>
    </div>
  </div>
	<% end %>
	
  <div class="control-group">
    <%= f.label :track_results, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :track_results %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/practices/complete.html.erb
<h1>Complete practice</h1>

<%= render 'complete_form' %>

<%= link_to 'Back', team_workout_practices_path(@team, @workout) %>

app/views/practices/edit.html.erb
<h1>Editing practice</h1>

<%= render 'form' %>

<%= link_to 'Back', team_workout_practices_path(@team, @workout) %>

app/views/practices/index.html.erb
<h1>Listing practices</h1>

<table class="table table-striped">
<thead>
	  <tr>
    <th>Scheduled date</th>
    <th>Scheduled time</th>
    <th>Player</th>
    <th>Track results</th>
    <th>Workout</th>
    <th></th>
		<th></th>
		<th></th>
    <th></th>
  </tr>
</thead><tbody>
<% @practices.each do |practice| %>
  <tr>
    <td><%= practice.scheduled_date %></td>
    <td><%= practice.scheduled_time %></td>
    <td><%= practice.member.name if practice.member %></td>
    <td><%= practice.track_results %></td>
    <td><%= practice.workout.name %></td>
    <td><%= link_to 'Show', team_workout_practice_path(@team, @workout, practice) %></td>
		<% unless practice.complete %>
    <td><%= link_to 'Complete', complete_team_workout_practice_path(@team, @workout, practice) %></td>
		<% end %>
    <td><%= link_to 'Edit', edit_team_workout_practice_path(@team, @workout, practice) %></td>
    <td><%= link_to 'Cancel', team_workout_practice_path(@team, @workout, practice), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Practice', new_team_workout_practice_path(@team, @workout) %>

app/views/practices/new.html.erb
<h1>New practice</h1>

<%= render 'form' %>

<%= link_to 'Back', team_workout_practices_path(@team, @workout) %>

app/views/practices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Workout:</b>
  <%= @practice.workout.name %>
</p>
<p <% if @practice.complete %>class="strike"<% end %>>
  <b>Scheduled date:</b>
  <%= @practice.scheduled_date %>
</p>

<p <% if @practice.complete %>class="strike"<% end %>>
  <b>Scheduled time:</b>
  <%= @practice.scheduled_time %>
</p>

<% if @practice.member %>
<p>
  <b>Member:</b>
  <%= @practice.member.name %>
</p>
<% end %>

<p>
  <b>Track results:</b>
  <%= @practice.track_results %>
</p>

<p>
	<%= @practice.notes %>
</p>

<% if @practice.track_results and @practice.complete %>
<table class="table table-striped">
	<thead>
		<th></th>
		<th>Activity</th>
		<th>Made</th>
		<th>Max</th>
		</thead>
		<tbody>
		<% @practice.results.each do |r| %>
		<tr>
			<td>
				<%= r.plan_position %>.
			</td>
			<td><%= r.activity_name %></td>
			<td><%= r.reps %></td>
			<td><%= r.plan_reps %></td>
		</tr>
	<% end %>
	</table>
<% end %>

<%= link_to 'Edit', edit_team_workout_practice_path(@team, @workout, @practice) %> |