config/routes.rb
Coachio::Application.routes.draw do

  devise_for :users

  resources :teams do
    match "practices" => "teams#practices"
    resources :activities
    resources :goals do
      resources :progresses
    end
    resources :members
    resources :workouts do
      resources :practices do
        resources :results # Not sure I need these routes, probably just handle it in practice
        get 'complete', :on => :member
      end
      resources :plans
    end
  end
  
  root :to => "home#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :team
  has_many :plans
  has_many :workouts, :through => :plans
  attr_accessible :group, :minutes, :name
  validates :name,  :presence => true
  
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :team
  has_many :progresses
  attr_accessible :active, :description, :name, :team
  validates :name,  :presence => true
  
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :team
  has_many :practices
  attr_accessible :first_name, :last_name, :number, :player, :position
  validates :first_name,  :presence => true
  validates :last_name,  :presence => true
  
  def name
    first_name + ' ' + last_name
  end
  
  def practice_results
    results = practices.collect{|p| p.results}
    puts results
    if results
      results.flatten.sort!{|a,b| a.plan_id <=> b.plan_id }
    else
      results
    end
  end
  
  
  def practice_results2
    results = practices.collect{|p| p.results}
    puts results
    if results
      results.flatten.sort!{|a,b| a.plan_id <=> b.plan_id }
    else
      results
    end
  end
  
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :activity
  belongs_to :workout
  has_many :practices
  default_scope :order => 'position ASC'
  attr_accessible :activity_id, :individual, :public, :workout_id, :position, :minutes , :reps
  validates :activity_id,  :presence => true
  #Not sure why but this fails the workout create, probably because its checking on build not save
  #validates :workout_id,  :presence => true
  
  def minutes
    activity.minutes
  end
end

app/models/practice.rb
class Practice < ActiveRecord::Base
  belongs_to :team
  belongs_to :member
  belongs_to :workout
  has_many :results
  accepts_nested_attributes_for :results,
      :allow_destroy => true,
      :reject_if     => :all_blank
  attr_accessible :scheduled_date, :scheduled_time, :track_results, :member_id, :complete, :notes, :results_attributes
  
  def results_totals
    # Get the totals of each activity totalled up
    puts 'hiii'
  end
  
end

app/models/progress.rb
class Progress < ActiveRecord::Base
  belongs_to :goal
  belongs_to :member
  attr_accessible :made, :total, :member_id
  validates :member_id,  :presence => true
  
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :practice
  belongs_to :plan
  attr_accessible :reps, :plan_id
  
  
  
  # Make methods for these then we can references them in the forms...
  def activity_name
    plan.activity.name
  end
  
  def plan_reps
    plan.reps
    #practice.workout.plans.find_by_activity_id(plan.activity.id).reps
  end
  
  
  def plan_position
    puts plan.to_json
    plan.position
    #practice.workout.plans.find_by_activity_id(plan.activity.id).position
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :city, :mascot, :name, :state, :kind, :description
  validates :name,  :presence => true
  has_many :members
  has_many :activities
  has_many :workouts
  has_many :goals
  has_many :practices

  def plans
    workouts.collect{|w| w.plans }.flatten
  end

  def location
    city + ', ' + state
  end
  
  def team_name
    name + ' ' + mascot
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :team
  has_many :practices
  has_many :plans
  has_many :activities, :through => :plans
  accepts_nested_attributes_for :plans,
      :allow_destroy => true,
      :reject_if     => :all_blank
  attr_accessible :group, :name, :plans_attributes
  validates :name,  :presence => true
  
  def length
    plans.collect{|p| p.minutes}.sum
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def setup_workout(workout)
    # Add extra activities to the plan
    2.times { workout.plans.build() }
    puts workout
    workout
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Coachio" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Coachio</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Teams", teams_path()  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div id="main" class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
					<% if notice %>
						<p id="notice" class="alert"><%= notice %></p>
					<% end %>
              <%= yield %>
            </div>

						<% if current_user %>

            <div class="span3">
              <div class="well sidebar-nav"><img src="/images/mask.gif" /> 
                <h3><%= current_user.email %></h3>
                <ul class="nav nav-list">
                  <li class="nav-header">User Links</li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
						<% end %>
						
						<% if @team and @team.name %>

            <div class="span3">
              <div class="well sidebar-nav"><img src="/images/mask.gif" /> 
                <h3><%= link_to @team.team_name, team_path(@team) %></h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Team Links</li>
                  <li><%= link_to "Activities", team_activities_path(@team)  %></li>
                  <li><%= link_to "Goals", team_goals_path(@team)  %></li>
                  <li><%= link_to "Roster", team_members_path(@team)  %></li>
                  <li><%= link_to "Practices", team_practices_path(@team)  %></li>
                  <li><%= link_to "Workout Bank", team_workouts_path(@team)  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
						<% end %>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; FAST Solutions 2012</p>
      </footer>
			
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/old_app.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coachio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>