config/routes.rb
Coachio::Application.routes.draw do

  devise_for :users

  resources :teams do
    match "practices" => "teams#practices"
    resources :activities
    resources :goals do
      resources :progresses
    end
    resources :members
    resources :workouts do
      resources :practices do
        resources :results # Not sure I need these routes, probably just handle it in practice
        get 'complete', :on => :member
      end
      resources :plans
    end
  end
  
  root :to => "home#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :team
  has_many :plans
  has_many :workouts, :through => :plans
  attr_accessible :group, :minutes, :name
  validates :name,  :presence => true
  
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :team
  has_many :progresses
  attr_accessible :active, :description, :name, :team
  validates :name,  :presence => true
  
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :team
  has_many :practices
  attr_accessible :first_name, :last_name, :number, :player, :position
  validates :first_name,  :presence => true
  validates :last_name,  :presence => true
  
  def name
    first_name + ' ' + last_name
  end
  
  def practice_results
    results = practices.collect{|p| p.results}
    puts results
    if results
      results.flatten.sort!{|a,b| a.plan_id <=> b.plan_id }
    else
      results
    end
  end
  
  
  def practice_results2
    results = practices.collect{|p| p.results}
    puts results
    if results
      results.flatten.sort!{|a,b| a.plan_id <=> b.plan_id }
    else
      results
    end
  end
  
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :activity
  belongs_to :workout
  has_many :practices
  default_scope :order => 'position ASC'
  attr_accessible :activity_id, :individual, :public, :workout_id, :position, :minutes , :reps
  validates :activity_id,  :presence => true
  #Not sure why but this fails the workout create, probably because its checking on build not save
  #validates :workout_id,  :presence => true
  
  def minutes
    activity.minutes
  end
end

app/models/practice.rb
class Practice < ActiveRecord::Base
  belongs_to :team
  belongs_to :member
  belongs_to :workout
  has_many :results
  accepts_nested_attributes_for :results,
      :allow_destroy => true,
      :reject_if     => :all_blank
  attr_accessible :scheduled_date, :scheduled_time, :track_results, :member_id, :complete, :notes, :results_attributes
  
  def results_totals
    # Get the totals of each activity totalled up
    puts 'hiii'
  end
  
end

app/models/progress.rb
class Progress < ActiveRecord::Base
  belongs_to :goal
  belongs_to :member
  attr_accessible :made, :total, :member_id
  validates :member_id,  :presence => true
  
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :practice
  belongs_to :plan
  attr_accessible :reps, :plan_id
  
  
  
  # Make methods for these then we can references them in the forms...
  def activity_name
    plan.activity.name
  end
  
  def plan_reps
    plan.reps
    #practice.workout.plans.find_by_activity_id(plan.activity.id).reps
  end
  
  
  def plan_position
    puts plan.to_json
    plan.position
    #practice.workout.plans.find_by_activity_id(plan.activity.id).position
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :city, :mascot, :name, :state, :kind, :description
  validates :name,  :presence => true
  has_many :members
  has_many :activities
  has_many :workouts
  has_many :goals
  has_many :practices

  def plans
    workouts.collect{|w| w.plans }.flatten
  end

  def location
    city + ', ' + state
  end
  
  def team_name
    name + ' ' + mascot
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :team
  has_many :practices
  has_many :plans
  has_many :activities, :through => :plans
  accepts_nested_attributes_for :plans,
      :allow_destroy => true,
      :reject_if     => :all_blank
  attr_accessible :group, :name, :plans_attributes
  validates :name,  :presence => true
  
  def length
    plans.collect{|p| p.minutes}.sum
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @team = Team.find(params[:team_id])
    @members = @team.members

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @team = Team.find(params[:team_id])
    @member = @team.members.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @team = Team.find(params[:team_id])
    @member = @team.members.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @team = Team.find(params[:team_id])
    @member = @team.members.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @team = Team.find(params[:team_id])
    @member = @team.members.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to team_members_path(@team), notice: 'member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @team = Team.find(params[:team_id])
    @member = @team.members.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to team_members_path(@team), notice: 'member was successfully created.' }
        #format.html { redirect_to @member, notice: 'member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def setup_workout(workout)
    # Add extra activities to the plan
    2.times { workout.plans.build() }
    puts workout
    workout
  end
end

app/views/members/_form.html.erb
<%= form_for([@team, @member], :html => { :class => 'form-horizontal' }) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :number, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :number, :class => 'number_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :player, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :player %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'Position (PG, Coach)', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :position %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                team_members_path(@team), :class => 'btn' %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', team_member_path(@team, @member) %> |
<%= link_to 'Back', team_members_path(@team) %>

app/views/members/index.html.erb
<div class="page-header">
<h2>Listing members</h2>
</div>
<% if @members.empty? %>
<h3>No team members yet. Why not add a few?</h3>
<% else %>
<table class="table table-striped">
<thead>  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Player</th>
    <th>Position</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead><tbody>
<% @members.each do |member| %>
  <tr>
    <td><%= member.number %></td>
    <td><%= member.name %></td>
    <td><%= member.player %></td>
    <td><%= member.position %></td>
    <td><%= link_to 'Show', team_member_path(@team, member) %></td>
    <td><%= link_to 'Edit', edit_team_member_path(@team, member) %></td>
    <td><%= link_to 'Destroy', team_member_path(@team, member), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</tbody>
</table>
<% end %>
<div class="page-actions">
<%= link_to 'New member', new_team_member_path(@team),:class => 'btn btn-primary' %>
</div>

app/views/members/new.html.erb
<div class="page-header">
	<h2>New team member</h2>
</div>

<%= render 'form' %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @member.name %>
</p>

<p>
  <b>Player:</b>
  <%= @member.player %>
</p>

<p>
  <b>Position:</b>
  <%= @member.position %>
</p>

<table class="table table-striped">
<thead><tr>
	<th>Date</th>
	<th>Activity</th>
	<th>Reps</th>
	</thead>
	<tbody>
<% @member.practice_results.each do |r| %>
	<tr>
		<td><%= link_to r.practice.scheduled_date, team_workout_practice_path(@team, r.plan.workout, r.practice.id) %></td>
		<td><%= r.plan.activity.name %></td>
		<td><%= r.reps %> / <%= r.plan.reps %></td>
	</tr>
<% end %>
</tbody>
</table>
<%= link_to 'Edit', edit_team_member_path(@team, @member) %> |
<%= link_to 'Back', team_members_path(@team) %>